{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fowarding.configname" . }}
  labels:
    {{- include "fowarding.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.config | nindent 4 }}
{{- end }}
