apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fowarding.fullname" . }}
  labels:
    {{- include "fowarding.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "fowarding.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.pod.podManagementPolicy }}
  updateStrategy:
    {{- toYaml .Values.pod.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "fowarding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.config }}
      annotations:
        {{- if .Values.config }}
        checksum/config: {{ .Values.config | sha1sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "fowarding.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.pod.ports | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.pod.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pod.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.pod.resources | nindent 12 }}
          env:
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            {{- if .Values.config }}
            - name: CONFIG_FILE
              value: /forwarding-config/config.yaml
            {{- end }}
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.config }}
            - name: config
              mountPath: /forwarding-config
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.config }}
        - name: config
          configMap:
            name: {{ include "fowarding.configname" . }}
        {{- end }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
